export const locationRows = [
  {
    id: 1,
    location: "Narangala",
    img: "/assets/Locations/Narangala_1.jpg",
    shortDes: "sdfdgfdgddsdfvvdvdfvdfvdfvddvdvdfvxvvvfvvvfvx",
    longDes: "fvfdsfdcs djf vvfs vfdvfd vfdv fdj jdf dfjfd ffd djfvdvd vfdjvf d v nvfdivnfdfi nfd ndnvfdvn fn fu nfvfnvdun  fnd f nffdnf n nf nfvndnf fn fd fndfu fud dn",
    province: "Central Province",
  },
  {
    id: 2,
    location: "Wangedigala",
    img: "/assets/Locations/Wangedigala_1.jpg",
    shortDes: "sdfdgfdgddsdfvvdvdfvdfvdfvddvdvdfvxvvvfvvvfvx",
    longDes: "fvfdsfdcs djf vvfs vfdvfd vfdv fdj jdf dfjfd ffd djfvdvd vfdjvf d v nvfdivnfdfi nfd ndnvfdvn fn fu nfvfnvdun  fnd f nffdnf n nf nfvndnf fn fd fndfu fud dn",
    province: "Central Province",
  },
  {
    id: 3,
    location: "Haritha Kanda",
    img: "/assets/Locations/HarithaKanda_1.jpg",
    shortDes: "sdfdgfdgddsdfvvdvdfvdfvdfvddvdvdfvxvvvfvvvfvx",
    longDes: "fvfdsfdcs djf vvfs vfdvfd vfdv fdj jdf dfjfd ffd djfvdvd vfdjvf d v nvfdivnfdfi nfd ndnvfdvn fn fu nfvfnvdun  fnd f nffdnf n nf nfvndnf fn fd fndfu fud dn",
    province: "Central Province",
  },
  {
    id: 4,
    location: "Chariot Path",
    img: "/assets/Locations/Narangala_1.jpg",
    shortDes: "sdfdgfdgddsdfvvdvdfvdfvdfvddvdvdfvxvvvfvvvfvx",
    longDes: "fvfdsfdcs djf vvfs vfdvfd vfdv fdj jdf dfjfd ffd djfvdvd vfdjvf d v nvfdivnfdfi nfd ndnvfdvn fn fu nfvfnvdun  fnd f nffdnf n nf nfvndnf fn fd fndfu fud dn",
    province: "Central Province",
  },
  {
    id: 5,
    location: "Gartmore",
    img: "/assets/Locations/Wangedigala_1.jpg",
    shortDes: "sdfdgfdgddsdfvvdvdfvdfvdfvddvdvdfvxvvvfvvvfvx",
    longDes: "fvfdsfdcs djf vvfs vfdvfd vfdv fdj jdf dfjfd ffd djfvdvd vfdjvf d v nvfdivnfdfi nfd ndnvfdvn fn fu nfvfnvdun  fnd f nffdnf n nf nfvndnf fn fd fndfu fud dn",
    province: "Central Province",
  },
];